config/routes.rb
Rails.application.routes.draw do
  root "friends#index"
  resources :friends
  get "home/about"
  get "home/contacts"
  get "home/search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show update edit destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, success: "#{@friend[:First_name].upcase} was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "#{@friend[:First_name].upcase} was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, error: "#{@friend[:First_name].upcase} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:First_name, :Last_name, :Email, :Facebook, :Who_is)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @pr = Friend.where("First_name LIKE ?", "%i%").order(Last_name: :desc).pluck(:Last_name)
  end

  def contacts
  end

  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :First_name %>
    <%= form.text_field :First_name, placeholder: "First name", class: "form-control" %>
  </div>

  <div class="field form-group">
    <% form.label :Last_name %>
    <%= form.text_field :Last_name, placeholder: "Last name", class: "form-control" %>
  </div>

  <div class="field form-group" type="email">
    <% form.label :Email %>
    <%= form.text_field :Email, placeholder: "name@example.com", class: "form-control" %>
  </div>

  <div class="field form-group">
    <% form.label :Facebook %>
    <%= form.text_field :Facebook, placeholder: "Facebook", class: "form-control" %>
  </div>

  <div class="field form-group">
    <% form.label :Who_is %>
    <%= form.text_field :Who_is, placeholder: "Description", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br/>

<%= render "form", friend: @friend %>

<%= link_to "Show", @friend, class: "btn btn-secondary" %> |=|
<%= link_to "Back", friends_path, class: "btn btn-secondary" %>

app/views/friends/index.html.erb
<br/>
<br/>
You have a total of : <%= @friends.count%> Friends
<table class="table table-striped table-hover table-bordered table-responsive border-info">
    <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Facebook</th>
      <th>Description</th>
      <th colspan="3">Features</th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td> <u><%= friend.id%></u> :: <%= friend.First_name %></td>
        <td><%= friend.Last_name %></td>
        <td><%= friend.Email %></td>
        <td><%= friend.Facebook %></td>
        <td><%= friend.Who_is %></td>
        <td><%= link_to "Show", friend %></td>
        <td><%= link_to "Edit", edit_friend_path(friend) %></td>
        <td><%= link_to "Destroy", friend, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

<%= link_to "New Friend", new_friend_path, class: "btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>
<br/>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

app/views/friends/show.html.erb
<br/>
<br/>

<div class="card col-sm-10">
  <div class="card-body">
    <h5 class="card-title ">
      First_name :: <strong> <%= @friend.First_name %> </strong>
      <br/>Last_name :: <strong><%= @friend.Last_name %></strong>
    </h5>
    <br/>
    <hr/>
    <h6 class="card-text text-center">
      <%= @friend.Email %> ||
      <%= @friend.Facebook %> ||
      <%= @friend.Who_is %>||
      <br/>
      |Member Since :: <%= @friend[:created_at] %>|
      <br/>
      <%if @friend[:updated_at].class != NilClass and (@friend[:created_at] != @friend[:updated_at]) %>
      <%="|Status Updated at :: " + @friend[:updated_at].to_s.split[0]+" Hour : "+ @friend[:updated_at].to_s.split[1] %>|
      <%end%>
    </h6>
    <br/>
    <br/>
    <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-secondary" %> |
    <%= link_to "Back", friends_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/home/_footer.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-center" href="#">Thanks for being with Me</a>
    <a class="navbar-text " href="#"> <%= Date.today.year%></a>
  </div>
</nav>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to "Friends App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "About Us", home_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Contact Us", home_contacts_path, class: "nav-link" %>        
        </li>
        <li class="nav-item">
            <%= link_to "All Friends", friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Add friend", new_friend_path, class: "nav-link" %>
        </li>
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <%# <button class="btn btn-outline-success" type="submit">Search</button> %>
        <%= link_to "Search", home_search_path, class: "btn btn-outline-success"%>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>
You want to know more about us ????
</h1>
<%= @pr %>

app/views/home/contacts.html.erb
<h1> You can reach us out at  Ouagadougou</h1>

app/views/home/index.html.erb
<h1> WELOCOME BUDIES AND WELOCOME AGAIN</h1>

app/views/home/search.html.erb
<h2>Finded friends</h2>

<script>
document.querySelector('.form-control')
</script>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <%= render "home/header" %>
    <br/>
    <% if notice %>
      <%= render "layouts/alerts"%>
    <%end%>
    <div class="container">
    <h2> It's :
              <%# <% while true do%> 
              <% time = Time.now() %>
              <%=  time %>
              <%# <% sleep(1) %>
              <%# <% end%>
                
     </h2>
    <hr/>
    <%# <%= image_tag "pno.jpg", class:"rounded  border border-secondary"%>
      <%= yield %>
    </div>
    <%= render "home/footer"%>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>